Race in testCheckpointForUnknownTaskGroup() of KafkaSupervisorTest.
          The stacktrace is:
2018-08-10T00:03:11,557 ERROR [KafkaSupervisor-testDS] io.druid.indexing.kafka.supervisor.KafkaSupervisor - KafkaSupervisor[testDS] failed to handle notice: {class=io.druid.indexing.kafka.supervisor.KafkaSupervisor, exceptionType=class io.druid.java.util.common.ISE, exceptionMessage=WTH?! cannot find taskGroup [0] among all taskGroups [{}], noticeClass=CheckpointNotice}
io.druid.java.util.common.ISE: WTH?! cannot find taskGroup [0] among all taskGroups [{}]
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor$CheckpointNotice.isValidTaskGroup(KafkaSupervisor.java:686) ~[classes/:?]
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor$CheckpointNotice.handle(KafkaSupervisor.java:638) ~[classes/:?]
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor$2.run(KafkaSupervisor.java:363) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

The corresponding code is:
Assert.assertNotNull(serviceEmitter.getStackTrace());
So, the issue is, serviceEmitter.getStackTrace() can return null when this check is called, so the test should wait for the stacktrace to be set.
      