Step not failing on org.springframework.transaction.UnexpectedRollbackException.
The transaction is timing out for a read by the reader in a step due to a lock. 
The transaction manager marks the out come of the transaction to be rollback only. 
Once the lock is released and the reader returns  a org.springframework.transaction.UnexpectedRollbackException is thrown while updating the chunk to database. 
Batch is considering this exception to be a non fatal exception and is continuing with the next chunk just by logging the exception at a debug level. 
Instead ity should fail the step I guess.
Problem : I am loosing all the records in that chunk. 
I changed the org.springframework.batch.core.step.item.SimpleRetryExceptionHandler.java's constructor like:
public SimpleRetryExceptionHandler(RetryPolicy retryPolicy, ExceptionHandler exceptionHandler, Collection&lt;Class&lt;? extends Throwable&gt;&gt; fatalExceptionClasses) 
{
		this.retryPolicy = retryPolicy;
		this.exceptionHandler = exceptionHandler;
		fatalExceptionClasses.add(org.springframework.transaction.UnexpectedRollbackException.class);
		this.fatalExceptionClassifier = new BinaryExceptionClassifier(fatalExceptionClasses);
	}

and tested. Now it is failing the step.
